'use client';

/* ==========================================================
   SIGNATURE ANIMATION — the signature is rendered fully intact,
   exactly as traced (see lib/signaturePath.ts, generated by
   scripts/generate-signature-path.mjs from the site's own Caveat
   font at "Phanindra"). Strokes are never drawn or path-traced;
   only a horizontal clip-path mask sweeps left → right to reveal
   the already-complete letterform, like a curtain lifting.

   The tagline lives here too (not in NoteSection) so its fade-in
   can be timed precisely off the mask's completion.

   IMPORTANT: the scroll-visibility check (useInView) watches the
   *outer, unclipped* wrapper — never the clipped element itself.
   If it watched the clipped element, its rendered width would be
   0px until revealed, so its measured visibility could never
   reach the reveal threshold: a deadlock where the animation that
   is supposed to reveal it is also the thing gating its own start.

   Replays every time it scrolls into view (leaving view resets it
   instantly, no transition, so the next entry reveals fresh).
   ========================================================== */

import { useEffect, useRef } from 'react';
import { motion, useAnimation, useInView } from 'framer-motion';
import { NOTE } from '@/lib/content';
import { SIGNATURE_PATH } from '@/lib/signaturePath';
import { prefersReducedMotion } from '@/lib/utils';

if (process.env.NODE_ENV !== 'production' && SIGNATURE_PATH.text !== NOTE.signature) {
  console.warn(
    `SignatureAnimation: lib/signaturePath.ts was traced from "${SIGNATURE_PATH.text}" but NOTE.signature is now "${NOTE.signature}". ` +
      'Run `node scripts/generate-signature-path.mjs` to re-trace it.'
  );
}

// Smooth, even, symmetric deceleration — the reveal stays visibly
// gradual across the full 1.6s instead of front-loading into the
// first third (an expo-style curve looks "snappy", not "slow").
const REVEAL_EASE: [number, number, number, number] = [0.65, 0, 0.35, 1];
const REVEAL_DURATION = 1.6;

export default function SignatureAnimation() {
  const wrapRef = useRef<HTMLDivElement>(null);
  const isInView = useInView(wrapRef, { amount: 0.6, once: false });
  const controls = useAnimation();
  const reduceMotion = typeof window !== 'undefined' && prefersReducedMotion();

  useEffect(() => {
    if (reduceMotion) {
      controls.set('revealed');
      return;
    }
    if (isInView) {
      controls.set('hidden');
      controls.start('revealed');
    } else {
      controls.set('hidden');
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isInView, reduceMotion]);

  return (
    <div className="note-signature-wrap" ref={wrapRef}>
      <motion.div
        className="note-signature-mask"
        initial="hidden"
        animate={controls}
        variants={{
          // The letterform itself never changes — only the clip mask moves.
          // clip-path: inset(top right bottom left). Sweeping the right
          // inset from 100% -> 0% uncovers the already-rendered signature
          // left to right, with a clean, hard edge (no blur/glow).
          hidden: { clipPath: 'inset(0% 100% 0% 0%)' },
          revealed: {
            clipPath: 'inset(0% 0% 0% 0%)',
            transition: { duration: REVEAL_DURATION, ease: REVEAL_EASE },
          },
        }}
      >
        <svg
          className="note-signature-svg"
          viewBox={`0 0 ${SIGNATURE_PATH.width} ${SIGNATURE_PATH.height}`}
          preserveAspectRatio="xMinYMid meet"
          aria-hidden="true"
          focusable="false"
        >
          <path
            d={SIGNATURE_PATH.d}
            fill="var(--accent)"
            fillOpacity={1}
            fillRule="nonzero"
          />
        </svg>
      </motion.div>
      <span className="visually-hidden">Signed, {NOTE.signature}</span>

      <motion.p
        className="note-motto"
        initial="hidden"
        animate={controls}
        variants={{
          hidden: { opacity: 0, y: 6 },
          revealed: {
            opacity: 1,
            y: 0,
            transition: { duration: 0.7, ease: 'easeOut', delay: REVEAL_DURATION },
          },
        }}
      >
        {NOTE.motto}
      </motion.p>
    </div>
  );
}
